name: Validate to Salesforce (Username-Password Auth)
on:
  pull_request:
    branches:
      - Salesforce-Main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global
        
      # 4. Verify that the Salesforce CLI has been installed properly.
      - name: Check Salesforce CLI version
        run: sfdx --version
      
        # How to Get the SFDX_AUTH_URL?
        # Goto VS Code and Authorize the org using the command:
        # sfdx force:auth:web:login -a deployOrg
        # After successful login. In VS Code, In Terminal, run the command for the auth URL:
        # sfdx force:org:display --targetusername LWCLearningOrg --verbose
      - name: Authenticate to Salesforce using Auth URL
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth-url.txt
          sfdx force:auth:sfdxurl:store -f auth-url.txt -s -a deployOrg

      - name: Validate metadata
        run: |
          sfdx force:source:deploy -c -p force-app
